services:
  # Frontend Service
  - type: web
    name: speaksutra-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: VITE_RAZORPAY_KEY_SECRET
        sync: false

  # Backend Service
  - type: web
    name: speaksutra-backend
    env: node
    plan: free
    buildCommand: cd src/server && npm install
    startCommand: cd src/server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: VITE_RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: PORT
        value: 3000 